// Package config centralises paths, tunables and runtime settings for recogn.
package config

import (
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"
)

// Config holds all runtime settings. Paths are resolved relative to the
// working directory the binary is launched from, so running `recogn` from the
// repository root keeps people/, models/ and data/ side by side.
type Config struct {
	PeopleDir string  // root of per-person photo folders
	ModelsDir string  // directory holding the ONNX models
	DataDir   string  // directory for the generated face database
	DBPath    string  // path to the bbolt face database file (faces.db)
	DetModel  string  // SCRFD detector ONNX filename (inside ModelsDir)
	EmbModel  string  // ArcFace embedder ONNX filename (inside ModelsDir)
	Threshold float64 // cosine-similarity threshold for a positive match
	Addr      string  // listen address for `serve`
	// Concurrency is how many model Runs may execute in parallel (the
	// engine's inference gate) and the default worker count for batch jobs
	// (enrollment scan, CLI recognize, multi-upload). 0 = auto
	// (DefaultConcurrency in internal/engine).
	Concurrency int

	// AdminPasswordHash enables password admin-auth when non-empty: an
	// argon2id PHC string of the admin password (env
	// RECOGN_ADMIN_PASSWORD_HASH, trimmed; empty means unset). Generate it
	// with `recogn hash-password`. The plaintext password is never stored;
	// only the hash travels in the environment. Together with registered
	// passkeys it gates the admin API surface; when neither is set the
	// server stays fully public (open mode).
	AdminPasswordHash string
	// SessionTTL is the (sliding) lifetime of a login session cookie
	// (RECOGN_SESSION_TTL duration; default 24h).
	SessionTTL time.Duration
	// WebAuthnRPID pins the passkey Relying Party ID (RECOGN_WEBAUTHN_RPID).
	// Empty ⇒ derive per-request from the request Host minus port, so the
	// default works on localhost and behind a reverse proxy alike.
	WebAuthnRPID string
	// WebAuthnOrigin pins the passkey expected client origin
	// (RECOGN_WEBAUTHN_ORIGIN, e.g. https://recogn.example.com). Empty ⇒
	// derive per-request: scheme from X-Forwarded-Proto (else http) plus the
	// request Host.
	WebAuthnOrigin string
	// WebAuthnRPName is the human-readable Relying Party name shown by
	// browsers during passkey ceremonies (RECOGN_WEBAUTHN_RP_NAME).
	WebAuthnRPName string
	// TrustedProxyCIDRs is the opt-in list of reverse-proxy CIDRs the login
	// rate limiter may trust for client-IP extraction
	// (RECOGN_TRUSTED_PROXY_CIDR, comma-separated). Empty (default) keys
	// rate limiting on the network peer and ignores X-Forwarded-For, which
	// means every client behind one proxy shares a bucket.
	TrustedProxyCIDRs string
}

// Default returns a Config populated from defaults, environment and flags.
// Flags are only parsed once (main calls this after flag.Parse).
func Default() Config {
	wd, _ := os.Getwd()
	cfg := Config{
		PeopleDir: envOr("RECOGN_PEOPLE_DIR", filepath.Join(wd, "people")),
		ModelsDir: envOr("RECOGN_MODELS_DIR", filepath.Join(wd, "models")),
		DataDir:   envOr("RECOGN_DATA_DIR", filepath.Join(wd, "data")),
		DetModel:  envOr("RECOGN_DET_MODEL", "det_10g.onnx"),
		EmbModel:  envOr("RECOGN_EMB_MODEL", "w600k_r50.onnx"),
		Threshold: envFloat("RECOGN_THRESHOLD", 0.45),
		Addr:      envOr("RECOGN_ADDR", ":8080"),
	}
	cfg.Concurrency = envInt("RECOGN_CONCURRENCY", 0)
	cfg.DBPath = filepath.Join(cfg.DataDir, "faces.db")

	// Admin auth (empty by default → open mode, everything public).
	// RECOGN_ADMIN_PASSWORD_HASH holds an argon2id PHC hash generated by
	// `recogn hash-password` — never the plaintext password.
	cfg.AdminPasswordHash = strings.TrimSpace(os.Getenv("RECOGN_ADMIN_PASSWORD_HASH")) // whitespace-only ⇒ unset
	cfg.SessionTTL = envDuration("RECOGN_SESSION_TTL", 24*time.Hour)                   // unparsable/unset ⇒ 24h
	cfg.WebAuthnRPID = envOr("RECOGN_WEBAUTHN_RPID", "")                               // "" ⇒ derive from request Host
	cfg.WebAuthnOrigin = envOr("RECOGN_WEBAUTHN_ORIGIN", "")                           // "" ⇒ derive from Host + X-Forwarded-Proto
	cfg.WebAuthnRPName = envOr("RECOGN_WEBAUTHN_RP_NAME", "recogn")                    // shown by browsers during ceremonies
	cfg.TrustedProxyCIDRs = strings.TrimSpace(os.Getenv("RECOGN_TRUSTED_PROXY_CIDR"))  // "" ⇒ peer-keyed rate limiting
	return cfg
}

// DetModelPath returns the absolute path to the detector model.
func (c Config) DetModelPath() string { return filepath.Join(c.ModelsDir, c.DetModel) }

// EmbModelPath returns the absolute path to the embedder model.
func (c Config) EmbModelPath() string { return filepath.Join(c.ModelsDir, c.EmbModel) }

func envOr(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}

func envFloat(key string, def float64) float64 {
	if v := os.Getenv(key); v != "" {
		if f, err := strconv.ParseFloat(v, 64); err == nil {
			return f
		}
	}
	return def
}

// envInt parses an integer environment variable, falling back to def when it
// is unset or unparsable.
func envInt(key string, def int) int {
	if v := os.Getenv(key); v != "" {
		if n, err := strconv.Atoi(v); err == nil {
			return n
		}
	}
	return def
}

// envDuration parses a time.Duration environment variable, falling back to
// def when it is unset or unparsable.
func envDuration(key string, def time.Duration) time.Duration {
	if v := os.Getenv(key); v != "" {
		if d, err := time.ParseDuration(v); err == nil {
			return d
		}
	}
	return def
}
